-- Seed historical_analogies with canonical records used by Scenario Simulator
INSERT INTO public.historical_analogies (country, period, defense_trend, emissions_trend, industry_effect, what_followed)
VALUES
('United States', '2001-2008', 'Defense spending rose approximately 80 percent following the September 11 attacks.', 'Industrial energy demand increased and emissions rose approximately 8 percent during the period.', 'Defense manufacturing expanded significantly with increased procurement and military operations.', 'Sustained defense sector growth and increased industrial activity.'),
('Germany', '1990-1998', 'Defense spending declined approximately 40 percent following reunification.', 'Emissions dropped sharply due to industrial restructuring in former East Germany.', 'Heavy industry underwent significant modernization and consolidation.', 'Lower emissions and economic restructuring across eastern regions.'),
('India', '2010-2018', 'Defense budget grew around 6 percent annually during modernization efforts.', 'National emissions increased approximately 40 percent due to industrial expansion.', 'Manufacturing and infrastructure sectors expanded rapidly.', 'Increased industrial output and economic growth alongside higher emissions.'),
('United Kingdom', '2010-2015', 'Defense spending was reduced under austerity measures.', 'Emissions declined approximately 15 percent while renewable energy adoption increased.', 'Resources shifted toward clean energy and efficiency initiatives.', 'Lower carbon intensity and growth in renewable sectors.'),
('Saudi Arabia', '2016-2022', 'Domestic defense spending increased while Vision 2030 reforms progressed.', 'Emissions growth slowed due to energy reform measures.', 'Economic diversification initiatives expanded beyond oil dependence.', 'Mixed defense expansion with gradual energy transition policies.'),
('China', '2005-2015', 'Defense spending more than doubled.', 'Emissions increased roughly 70 percent during heavy industrial expansion.', 'Manufacturing capacity and export industries grew rapidly.', 'Large-scale economic growth accompanied by substantial emissions increases.'),
('Sweden', '2022-2025', 'Defense spending increased toward NATO target levels.', 'Emissions remained relatively stable due to parallel green investment programs.', 'Green steel initiatives and energy innovation continued alongside defense expansion.', 'Defense growth without major emissions acceleration.'),
('United States', '1991-1999', 'Post-Cold War defense reductions occurred across multiple military programs.', 'Emissions remained comparatively stable.', 'Military production slowed while technology sectors expanded.', 'Economic diversification and reduced defense dependency.')
ON CONFLICT DO NOTHING;
